[package]
name = "repeating_key_xor"
version = "0.1.0"
authors = ["Patrick Elsen <pelsen@xfbs.net>"]

[dependencies]
hex_to_base64 = { path = "../hex_to_base64" }
single_byte_xor = { path = "../single_byte_xor" }
itertools = "0.4.13"
